Renamed toplevel to "giflib" due to vendor issues.
Originally I'd just called it 'gif', but when I vendored the package in to
my project, I got this error:

File "vendor/ocaml-gif/gif/gif.ml-gen", line 1:
Error: Could not find the .cmi file for interface
       vendor/ocaml-gif/gif/gif.mli.

After trying a bunch of things I found renaming the top level made the
issue go away.